name: Build APK

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Generate Changelog
        id: changelog
        run: |
          # Get commits since last release or last 10 commits if no release exists
          CHANGELOG=$(git log -10 --pretty=format:"- %s (%h)" --reverse)
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Get current date
        id: date
        run: echo "BUILD_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Rename APK
        run: |
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/LinkwardenShare.apk

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: LinkwardenShare
          path: app/build/outputs/apk/debug/LinkwardenShare.apk

      - name: Create Release
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/debug/LinkwardenShare.apk
          tag_name: v${{ github.run_number }}
          name: Build ${{ github.run_number }}
          draft: false
          prerelease: true
          generate_release_notes: false
          body: |
            This is the latest automated build of Linkwarden Share Helper.

            **App Information:**
            - Version Code: ${{ github.run_number }}
            - Build Date: ${{ env.BUILD_DATE }}
            - Minimum Android Version: 6.0 (API 23)

            **Recent Changes:**
            ${{ env.CHANGELOG }}

            **Note:** This is a development build and may contain bugs.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            app/build/outputs/
            app/build/reports/
