name: CI/CD Pipeline

on:
  push:
    branches: [ master, dev, 'feat/*', 'hotfix/*' ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run tests
        run: ./gradlew test

  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Generate version number
        id: version
        run: |
          YEAR=$(date +'%Y')
          MONTH=$(date +'%m')
          DAY=$(date +'%d')
          COMMITS=$(git rev-list --count HEAD)
          if [[ "$GITHUB_REF" == "refs/heads/master" ]]; then
            VERSION="1.$YEAR$MONTH.$DAY$COMMITS"
          elif [[ "$GITHUB_REF" == "refs/heads/dev" ]]; then
            VERSION="0.$YEAR$MONTH.$DAY$COMMITS-dev"
          else
            SAFE_BRANCH=$(echo "$GITHUB_REF" | sed 's/[^a-zA-Z0-9._-]/-/g')
            VERSION="0.$YEAR$MONTH.$DAY$COMMITS-$SAFE_BRANCH"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Build APK
        run: ./gradlew assembleDebug
      - name: Rename APK
        run: |
          mv app/build/outputs/apk/debug/app-debug.apk "app/build/outputs/apk/debug/LinkwardenShare-${{ steps.version.outputs.version }}.apk"
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: LinkwardenShare-${{ steps.version.outputs.version }}
          path: "app/build/outputs/apk/debug/LinkwardenShare-${{ steps.version.outputs.version }}.apk"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: LinkwardenShare-${{ needs.build.outputs.version }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: "LinkwardenShare-${{ needs.build.outputs.version }}.apk"
          tag_name: v${{ needs.build.outputs.version }}
          name: Release ${{ needs.build.outputs.version }}
          body: |
            This is a release version of LinkwardenShare.
            Branch: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}