name: CI/CD Pipeline

on:
  push:
    branches: [ master, dev, 'feat/*', 'hotfix/*' ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run tests
        run: ./gradlew test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Generate version number
        id: version
        run: |
          YEAR=$(date +'%Y')
          MONTH=$(date +'%m')
          DAY=$(date +'%d')
          COMMITS=$(git rev-list --count HEAD)
          BRANCH=${GITHUB_REF#refs/heads/}
          if [[ "$BRANCH" == "master" ]]; then
            VERSION="1.$YEAR$MONTH.$DAY$COMMITS"
          elif [[ "$BRANCH" == develop ]]; then
            VERSION="0.$YEAR$MONTH.$DAY$COMMITS-dev"
          elif [[ "$BRANCH" == release/* ]]; then
            VERSION="0.$YEAR$MONTH.$DAY$COMMITS-rc"
          else
            VERSION="0.$YEAR$MONTH.$DAY$COMMITS-$BRANCH"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build APK
        run: ./gradlew assembleDebug
      - name: Rename APK
        run: |
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/LinkwardenShare-${{ env.VERSION }}.apk
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: LinkwardenShare-${{ env.VERSION }}
          path: app/build/outputs/apk/debug/LinkwardenShare-${{ env.VERSION }}.apk

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master'))
    steps:
      - uses: actions/checkout@v4
      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: LinkwardenShare-${{ env.VERSION }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: LinkwardenShare-${{ env.VERSION }}.apk
          tag_name: v${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          draft: false
          prerelease: ${{ github.ref != 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
